# Data-X Spring 2019: Homework 06 

## Name : Junyan Tan
## SID : 3033370095
## Course (IEOR 135/290) : IEOR 135

### Machine Learning



In this homework, you will do some exercises with prediction. We will cover these algorithms in class, but this is for you to have some hands on with these in scikit-learn. You can refer - https://github.com/ikhlaqsidhu/data-x/blob/master/05a-tools-predicition-titanic/titanic.ipynb

Display all your outputs.


In [1]:
import numpy as np
import pandas as pd

In [2]:
 # machine learning libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.linear_model import Perceptron
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier



__ 1. Read __`diabetesdata.csv`__ file into a pandas dataframe. 
About the data: __

1. __TimesPregnant__: Number of times pregnant 
2. __glucoseLevel__: Plasma glucose concentration a 2 hours in an oral glucose tolerance test 
3. __BP__: Diastolic blood pressure (mm Hg)  
5. __insulin__: 2-Hour serum insulin (mu U/ml) 
6. __BMI__: Body mass index (weight in kg/(height in m)^2) 
7. __pedigree__: Diabetes pedigree function 
8. __Age__: Age (years) 
9. __IsDiabetic__: 0 if not diabetic or 1 if diabetic) 








In [3]:
#Read data & print the head
diabets = pd.read_csv("diabetesdata.csv")
diabets.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  IsDiabetic
0              6         148.0  72        0  33.6     0.627  50.0           1
1              1           NaN  66        0  26.6     0.351  31.0           0
2              8         183.0  64        0  23.3     0.672   NaN           1
3              1           NaN  66       94  28.1     0.167  21.0           0
4              0         137.0  40      168  43.1     2.288  33.0           1

**2. Calculate the percentage of Null values in each column and display it. **

In [4]:
percent_col = []
for i in range(len(diabets.columns)):
    percent_col.append(diabets.iloc[:, i].isna().sum() / len(diabets.iloc[:, i]))
pd.DataFrame(data=percent_col, columns=["Percentage of Null values"], index=diabets.columns)

Percentage of Null values
TimesPregnant                   0.000000
glucoseLevel                    0.044271
BP                              0.000000
insulin                         0.000000
BMI                             0.000000
Pedigree                        0.000000
Age                             0.042969
IsDiabetic                      0.000000

**3. Split __`data`__  into  __`train_df`__ and __`test_df`__  with 15% as test.**


In [5]:
train_df, test_df = train_test_split(diabets, test_size = 0.15)

**4. Display the means of the features in train and test sets. Replace the null values in  __`train_df`__ and __`test_df`__  with the mean of EACH feature column separately for train and test. Display head of the dataframes.**

In [6]:
print("Mean of train_df: ")
display(train_df.mean())
print("Mean of test_df: ")
display(test_df.mean())

Mean of train_df: 


TimesPregnant      3.828221
glucoseLevel     121.375602
BP                69.578221
insulin           81.374233
BMI               32.212577
Pedigree           0.472121
Age               33.028939
IsDiabetic         0.343558
dtype: float64

Mean of test_df: 


TimesPregnant      3.939655
glucoseLevel     119.000000
BP                66.448276
insulin           70.948276
BMI               30.756034
Pedigree           0.470500
Age               35.141593
IsDiabetic         0.379310
dtype: float64

In [7]:
train_df = train_df.fillna(value={col: train_df[col].mean() for col in train_df.columns})
test_df = test_df.fillna(value={col: test_df[col].mean() for col in test_df.columns})

In [8]:
train_df.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
179              5         130.0  82        0  39.1     0.956  37.0   
145              0         102.0  75        0   0.0     0.572  21.0   
90               1          80.0  55        0  19.1     0.258  21.0   
342              1           0.0  68        0  32.0     0.389  22.0   
359              1         196.0  76      249  36.5     0.875  29.0   

     IsDiabetic  
179           1  
145           0  
90            0  
342           0  
359           1

In [9]:
test_df.head()

TimesPregnant  glucoseLevel  BP  insulin   BMI  Pedigree   Age  \
20               3         126.0  88      235  39.3     0.704  27.0   
354              3          90.0  78        0  42.7     0.559  21.0   
197              3         107.0  62       48  22.9     0.678  23.0   
294              0         161.0  50        0  21.9     0.254  65.0   
1                1         119.0  66        0  26.6     0.351  31.0   

     IsDiabetic  
20            0  
354           0  
197           1  
294           0  
1             0

**5. Split __`train_df`__ & __`test_df`__   into  __`X_train`__, __`Y_train`__  and __`X_test`__, __`Y_test`__. __`Y_train`__  and __`Y_test`__ should only have the column we are trying to predict,  __`IsDiabetic`__.**

In [10]:
X_train = train_df.drop("IsDiabetic", axis=1)
Y_train = train_df["IsDiabetic"]
X_test = test_df.drop("IsDiabetic", axis=1)
Y_test = test_df["IsDiabetic"]

**6. Use this dataset to train perceptron, logistic regression and random forest models using 15% test split. Report training and test accuracies. Try different hyperparameter values for these models and see if you can improve your accuracies.**

In [11]:
# 6a. Logistic Regression
# Train the logistics regression model
lr = LogisticRegression(max_iter=1000, solver='lbfgs')
lr.fit(X_train, Y_train)

# Score the accuracy of the model
lr_train_accuracy = lr.score(X_train, Y_train)
lr_test_aaccuracy = lr.score(X_test, Y_test)

print('Training accuracy for logistics regression: ', lr_train_accuracy)
print('Test accuracy for logistics regression: ', lr_test_aaccuracy)

Training accuracy for logistics regression:  0.7806748466257669
Test accuracy for logistics regression:  0.7241379310344828


In [12]:
# 6b. Perceptron
pecp = Perceptron(max_iter=10000, tol=0.19)
pecp.fit(X_train, Y_train)
pecp_train_accuracy = pecp.score(X_train, Y_train)
pecp_test_accuracy = pecp.score(X_test, Y_test)
print('Training accuracy for Perceptron regression: ', pecp_train_accuracy)
print('Test accuracy for Perceptron regression: ', pecp_test_accuracy)

Training accuracy for Perceptron regression:  0.656441717791411
Test accuracy for Perceptron regression:  0.6206896551724138


In [13]:
# 6c. Random Forest
rf = RandomForestClassifier(n_estimators=500)
rf.fit(X_train, Y_train)
rf_train_accuracy = rf.score(X_train, Y_train)
rf_test_accuracy = rf.score(X_test, Y_test)
print('Training accuracy for Random Forest: ', rf_train_accuracy)
print('Test accuracy for Random Forest: ', rf_train_accuracy)

Training accuracy for Random Forest:  1.0
Test accuracy for Random Forest:  1.0


**7. For your logistic regression model - **

**a . Compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your train set and display it. Also display the predicted class for those samples from your logistic regression model trained before. **


In [14]:
lr.predict_log_proba(X_train[0:10])

array([[-9.21463448e-01, -5.07391952e-01],
       [-4.68061446e-03, -5.36666528e+00],
       [-1.73546546e-02, -4.06255931e+00],
       [-2.52327441e-03, -5.98345922e+00],
       [-1.99506517e+00, -1.46188055e-01],
       [-1.11520261e+00, -3.97272031e-01],
       [-5.21292404e-01, -9.00793151e-01],
       [-1.56708105e-01, -1.93070144e+00],
       [-1.15111793e+00, -3.80211172e-01],
       [-2.29471445e-01, -1.58451932e+00]])

In [15]:
lr.predict(X_train[0:10])

array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0])

**b . Now compute the log probability of classes in  __`IsDiabetic`__ for the first 10 samples of your test set and display it. Also display the predicted class for those samples from your logistic regression model trained before.
 (using the model trained on the training set)**


In [16]:
lr.predict_log_proba(X_test[0:10])

array([[-0.41787205, -1.07425087],
       [-0.21001031, -1.66376679],
       [-0.09249878, -2.42645275],
       [-0.76413272, -0.62686833],
       [-0.15047593, -1.96824684],
       [-0.07293001, -2.6544985 ],
       [-0.09393459, -2.41175623],
       [-0.04247905, -3.17990849],
       [-0.08574538, -2.49893948],
       [-0.515405  , -0.90946074]])

In [17]:
lr.predict(X_test[0:10])

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

**c . What can you interpret from the log probabilities and the predicted classes?**



We have the target value (0, 1) to classify "IsDiabetic" in our problem. From the log probabilities, we can see that the first value is the log probability to classify a "0", and the second value is the log probability to classify a "1" in this case. Hence the value of log proabilites of classes are corresponding to the probability of a class to be labeled.

**8. Is mean imputation is the best type of imputation (as we did in 4.) to use? Why or why not? What are some other ways to impute the data?**

Mean imputation is not the best type of imputation because it doesn't perserve the relationships between variables but it is very convenient and easy to implement. The relationship between variables could be over-estimated or under-estimated. Besides mean imputation, we can use Expectation-Maximization imputation which perserve the relationships between variables but this method still will potentially underestimate the standard error. Multiple Imputation and Maximum Likelihood are great ways to impute if we can fit with the right tools.

## Extra Credit (2 pts) - MANDATORY for students enrolled in IEOR 290


**9.  Implement the K-Nearest Neighbours (https://en.wikipedia.org/wiki/K-nearest_neighbors_algorithm) algorithm for k=1 from scratch in python (do not use KNN from existing libraries). KNN uses Euclidean distance to find nearest neighbors. Split your dataset into test and train as before. Also fill in the null values with mean of features as done earlier. Use this algorithm to predict values for 'IsDiabetic' for your test set. Display your accuracy. **

In [18]:
import csv
import random
import math
import operator
 
def euclideanDistance(instance1, instance2, length): 
    distance = 0
    for x in range(length):
        distance += pow((instance1[x] - instance2[x]), 2) 
        return math.sqrt(distance)
    
def getNeighbors(trainingSet, testInstance, k): 
    distances = []
    length = len(testInstance)-1
    for x in range(len(trainingSet)):
        dist = euclideanDistance(testInstance, trainingSet[x], length)
        distances.append((trainingSet[x], dist)) 
    distances.sort(key=operator.itemgetter(1)) 
    neighbors = []
    for x in range(k):
        neighbors.append(distances[x][0]) 
        return neighbors
    
def getResponse(neighbors): 
    classVotes = {}
    for x in range(len(neighbors)): 
        response = neighbors[x][-1] 
        if response in classVotes:
            classVotes[response] += 1 
        else:
            classVotes[response] = 1
    sortedVotes = sorted(classVotes.items(), key=operator.itemgetter(1))
    return sortedVotes[0][0]

In [19]:
predictions=[] 
k=1
correct = 0 
accuracy = 0

for i in range(len(test_df)):
    neighbors = getNeighbors(train_df.values, test_df.values[i], k) 
    result = getResponse(neighbors)
    predictions.append(result)
    if result == test_df.values[i][-1]:
        correct += 1
    accuracy = correct/float(len(test_df)) * 100.0
    
print('Accuracy: ' + repr(accuracy) + '%')

Accuracy: 68.10344827586206%
